version: '2'
services:
  couchbase:
    image: couchbase:4.1.0
    volumes:
      - ./couchbase/data:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  node:
    build: ./node
    links:
      - couchbase
    volumes:
      - /usr/src/app/node_modules
      - ./src:/usr/src/app
    ports:
      - 3010:3010
